name: yeti_movies
description: A new Flutter project
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  bloc: ^8.1.3
  build_runner: ^2.4.11
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  json_annotation: ^4.1.0
  
  tmdb_api: 
    path: packages/tmdb_api
  movie_repository:
    path: packages/movie_repository
  fpdart: ^1.1.0
  dio: ^5.5.0+1


dev_dependencies:
  flutter_lints: ^3.0.0
  bloc_test: ^9.1.6
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  json_serializable: 6.8.0
  flutter_image_test_utils: ^1.0.0
  



flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/launcher_icons/
