name: tmdb_api
description: A Dart API Client for the unofficial tmbd API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.4.3 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  lints: ^4.0.0
  test: ^1.24.0

dependencies:
  dio: ^5.5.0+1
  equatable: ^2.0.5
  http: ^1.2.1
  json_annotation: ^4.1.0
  meta: 1.12.0
