name: movie_repository
description: "A Dart package for the movie domain."
publish_to: none
version: 1.0.0

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  tmdb_api:
    path: ../tmdb_api

dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  lints: ^3.0.0
  test: ^1.24.0

